# coding: utf-8

"""
    order of cloud resources

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clouds_api import CloudsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCloudsApi(unittest.TestCase):
    """CloudsApi unit test stubs"""

    def setUp(self):
        self.api = CloudsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_cloud_by_id(self):
        """Test case for cancel_cloud_by_id

        method of deleting order in the cloud  # noqa: E501
        """
        pass

    def test_create_cloud(self):
        """Test case for create_cloud

        method of creating order in the cloud  # noqa: E501
        """
        pass

    def test_get_all_clouds(self):
        """Test case for get_all_clouds

        method of getting cloud resource  # noqa: E501
        """
        pass

    def test_get_order_by_id(self):
        """Test case for get_order_by_id

        method of getting order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
